---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-network-operator
  namespace: sriov-network-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-network-config-daemon
  namespace: sriov-network-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: sriov-network-operator
  namespace: sriov-network-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - sriov-network-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - serviceaccounts
  - roles
  - rolebindings
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sriov-network-config-daemon
  namespace: sriov-network-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - '*'
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - '*'
  - sriovnetworknodestates
  verbs:
  - '*'
- apiGroups:
    - security.openshift.io
  resourceNames:
    - privileged
  resources:
    - securitycontextconstraints
  verbs:
    - use
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
- apiGroups:
  - 'coordination.k8s.io'
  resources:
  - 'leases'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-webhook-sa
  namespace: sriov-network-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sriov-network-operator
  namespace: sriov-network-operator
subjects:
- kind: ServiceAccount
  name: sriov-network-operator
roleRef:
  kind: Role
  name: sriov-network-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sriov-network-config-daemon
  namespace: sriov-network-operator
subjects:
- kind: ServiceAccount
  name: sriov-network-config-daemon
roleRef:
  kind: Role
  name: sriov-network-config-daemon
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-webhook-sa
  namespace: sriov-network-operator
subjects:
- kind: ServiceAccount
  name: operator-webhook-sa
roleRef:
  kind: Role
  name: operator-webhook-sa
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriov-network-operator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: [namespaces, serviceaccounts]
  verbs: ["*"]
- apiGroups: ["k8s.cni.cncf.io"]
  resources: ["network-attachment-definitions"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: [clusterroles, clusterrolebindings]
  verbs: ["*"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["*"]
- apiGroups: ["sriovnetwork.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriov-network-config-daemon
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriov-network-operator
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: sriov-network-operator
subjects:
- kind: ServiceAccount
  namespace: sriov-network-operator
  name: sriov-network-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriov-network-config-daemon
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: sriov-network-config-daemon
subjects:
- kind: ServiceAccount
  namespace: sriov-network-operator
  name: sriov-network-config-daemon

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: supported-nic-ids
  namespace: sriov-network-operator
data:
  Intel_i40e_XXV710: "8086 158a 154c"
  Intel_i40e_25G_SFP28: "8086 158b 154c"
  Intel_i40e_10G_X710_SFP: "8086 1572 154c"
  Intel_i40e_XXV710_N3000: "8086 0d58 154c"
  Intel_i40e_40G_XL710_QSFP: "8086 1583 154c"
  Intel_ice_Columbiaville_E810-CQDA2_2CQDA2: "8086 1592 1889"
  Intel_ice_Columbiaville_E810-XXVDA4: "8086 1593 1889"
  Intel_ice_Columbiaville_E810-XXVDA2: "8086 159b 1889"
  Nvidia_mlx5_ConnectX-4: "15b3 1013 1014"
  Nvidia_mlx5_ConnectX-4LX: "15b3 1015 1016"
  Nvidia_mlx5_ConnectX-5: "15b3 1017 1018"
  Nvidia_mlx5_ConnectX-5_Ex: "15b3 1019 101a"
  Nvidia_mlx5_ConnectX-6: "15b3 101b 101c"
  Nvidia_mlx5_ConnectX-6_Dx: "15b3 101d 101e"
  Nvidia_mlx5_MT42822_BlueField-2_integrated_ConnectX-6_Dx: "15b3 a2d6 101e"
  Broadcom_bnxt_BCM57414_2x25G: "14e4 16d7 16dc"
  Broadcom_bnxt_BCM75508_2x100G: "14e4 1750 1806"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriov-network-operator
  namespace: sriov-network-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sriov-network-operator
  template:
    metadata:
      labels:
        name: sriov-network-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      serviceAccountName: sriov-network-operator
      priorityClassName: "system-node-critical"
      containers:
        - name: sriov-network-operator
          image: quay.io/openshift/origin-sriov-network-operator:4.12.0
          command:
          - sriov-network-operator
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SRIOV_CNI_IMAGE
              value: quay.io/openshift/origin-sriov-cni:4.12.0
            - name: SRIOV_INFINIBAND_CNI_IMAGE
              value: quay.io/openshift/origin-sriov-infiniband-cni:4.12.0
            - name: SRIOV_DEVICE_PLUGIN_IMAGE
              value: quay.io/openshift/origin-sriov-network-device-plugin:4.12.0
            - name: NETWORK_RESOURCES_INJECTOR_IMAGE
              value: quay.io/openshift/origin-sriov-dp-admission-controller:4.12.0
            - name: OPERATOR_NAME
              value: sriov-network-operator
            - name: SRIOV_NETWORK_CONFIG_DAEMON_IMAGE
              value: quay.io/openshift/origin-sriov-network-config-daemon:4.12.0
            - name: SRIOV_NETWORK_WEBHOOK_IMAGE
              value: quay.io/openshift/origin-sriov-network-webhook:4.12.0
            - name: RESOURCE_PREFIX
              value: openshift.io
            - name: ENABLE_ADMISSION_CONTROLLER
              value: "true"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELEASE_VERSION
              value: 4.12.0
            - name: SRIOV_CNI_BIN_PATH
              value: /opt/cni/bin
            - name: CLUSTER_TYPE
              value: kubernetes
            - name: WEBHOOK_CA_BUNDLE
              value: ""
