apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflared.fullname" . }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
data:
  config.yaml: |
    credentials-file: {{ .Values.credentialsFile }}
    {{- toYaml .Values.config | nindent 4 }}
