{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cloudflared.fullname" . }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      {{- include "cloudflared.selectorLabels" . | nindent 6 }}
{{- end }}
