#!/usr/bin/env bash

set -euo pipefail

VERSION=23.0.3-1

docker buildx build . \
       --progress=plain \
       -t "gitea.eevans.me/shosti/keycloak:$VERSION" \
       --platform=linux/amd64 \
       --push
