{{- range $volName, $vol := .Values.persistence }}
{{- with $ }}
{{- if $vol.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "odoo.fullname" . }}-{{ $volName }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml $vol.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $vol.size }}
  storageClassName: {{ $vol.storageClassName }}
{{- end }}
{{- end }}
{{- end }}
