apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "truenas-certupdate.labels" . | nindent 4 }}
spec:
  dnsNames:
    {{- toYaml .Values.dnsNames | nindent 4 }}
  issuerRef:
    {{- toYaml .Values.issuerRef | nindent 4 }}
  secretName: {{ .Values.tlsSecretName }}
