---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infra
      namespace: flux-system
  interval: 10m0s
  path: ./k8s/deploy/apps
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infra
      namespace: flux-system
  interval: 10m0s
  path: .
  prune: true
  sourceRef:
    kind: OCIRepository
    namespace: flux-system
    name: local-apps
