---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/deploy/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: eevans-infra
