---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  dependsOn:
    - name: config
      namespace: flux-system
  interval: 10m0s
  path: ./k8s/deploy/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus
  namespace: flux-system
spec:
  dependsOn:
    - name: config
      namespace: flux-system
  interval: 10m0s
  path: ./k8s/deploy/multus
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sriov-operator
  namespace: sriov-network-operator
spec:
  dependsOn:
    - name: multus
      namespace: flux-system
  interval: 10m0s
  path: ./k8s/deploy/sriov-operator
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cockroach-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/deploy/cockroach-operator
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clickhouse-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/deploy/clickhouse-operator
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/deploy/mariadb-operator
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  dependsOn:
    - name: config
      namespace: flux-system
  interval: 10m0s
  path: ./k8s/deploy/infra
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
