---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt-operator
  namespace: kubevirt
spec:
  dependsOn:
    - name: config
      namespace: flux-system
  interval: 10m0s
  path: ./k8s/deploy/kubevirt-operator
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  dependsOn:
    - name: kubevirt-operator
      namespace: kubevirt
  interval: 10m0s
  path: ./k8s/deploy/kubevirt
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
