---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: eevans-infra
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
