---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-state
  namespace: flux-system
spec:
  dependsOn:
    - name: config
      namespace: flux-system
  interval: 10m0s
  path: ./k8s/deploy/clusters/lan
  prune: true
  sourceRef:
    kind: GitRepository
    name: eevans-infra
