---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-snapshotter
  namespace: kube-system
spec:
  interval: 10m0s
  path: ./k8s/deploy/csi-snapshotter
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-operator
  namespace: rook-ceph
spec:
  dependsOn:
    - name: config
      namespace: flux-system
  interval: 10m0s
  path: ./k8s/deploy/rook-operator
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-storage
  namespace: rook-ceph
spec:
  dependsOn:
    - name: rook-operator
      namespace: rook-ceph
    - name: csi-snapshotter
      namespace: kube-system
  interval: 10m0s
  path: ./k8s/deploy/rook-storage
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: eevans-infra
