apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-windows
  namespace: winvm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
