# Default values for dnsupdate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

schedule: '*/5 * * * *'

image:
  repository: harbor.eevans.me/library/dnsupdate
  tag: v1
  pullPolicy: IfNotPresent

host: lan.example.com
zoneName: example.com
apiTokenSecret: cloudflare-credentials

resources:
  requests:
    memory: 128Mi
    cpu: 0.5
  limits:
    memory: 128Mi
    cpu: 0.5

nameOverride: ""
fullnameOverride: ""
