---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clickhouse-coordinator
  namespace: clickhouse
spec:
  interval: 5m
  chart:
    spec:
      chart: zookeeper
      version: 12.3.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 3
    persistence:
      enabled: true
      size: 1Gi
      storageClass: local-drive
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
---
# apiVersion: clickhouse.altinity.com/v1
# kind: ClickHouseInstallation
# metadata:
#   name: clickhouse
#   namespace: clickhouse
# spec:
#   configuration:
#     clusters:
#       - name: clickhouse
