---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clickhouse-coordinator
  namespace: clickhouse
spec:
  interval: 5m
  chart:
    spec:
      chart: zookeeper
      version: 12.3.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 3
    persistence:
      enabled: true
      size: 1Gi
      storageClass: local-drive
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  configuration:
    zookeeper:
      nodes:
      - host: clickhouse-coordinator-zookeeper-0.clickhouse-coordinator-zookeeper-headless
      - host: clickhouse-coordinator-zookeeper-1.clickhouse-coordinator-zookeeper-headless
      - host: clickhouse-coordinator-zookeeper-2.clickhouse-coordinator-zookeeper-headless
    clusters:
      - name: default
        templates:
          clusterServiceTemplate: default
          podTemplate: default
          serviceTemplate: default
          dataVolumeClaimTemplate: default
        layout:
          shardsCount: 1
          replicasCount: 2
  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          storageClassName: local-drive
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
    podTemplates:
      - name: default
        metadata:
          labels:
            app.kubernetes.io/name: clickhouse
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.9.5.29-alpine
    serviceTemplates:
      - name: default
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
