---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  defaults:
    templates:
      serviceTemplate: default
  configuration:
    users:
      plausible/k8s_secret_password: users/plausible
      plausible/networks/ip:
        - 0.0.0.0/0
    zookeeper:
      nodes:
      - host: clickhouse-keeper-0.clickhouse-keeper.clickhouse.svc.cluster.local
      - host: clickhouse-keeper-1.clickhouse-keeper.clickhouse.svc.cluster.local
      - host: clickhouse-keeper-2.clickhouse-keeper.clickhouse.svc.cluster.local
    clusters:
      - name: default
        templates:
          clusterServiceTemplate: default
          podTemplate: default
          dataVolumeClaimTemplate: default
        layout:
          shardsCount: 1
          replicasCount: 2
  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          storageClassName: local-drive
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
    podTemplates:
      - name: default
        metadata:
          labels:
            app.kubernetes.io/name: clickhouse
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.9.5.29-alpine
              resources:
                requests:
                  cpu: 750m
                  memory: 1Gi
                limits:
                  memory: 1Gi
    serviceTemplates:
      - name: default
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: clickhouse
  policyTypes:
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              eevans.me/clickhouse-access: "true"
      ports:
        - port: 8123
        - port: 9000
    - from:
        - podSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - podSelector: {}
