---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commento
  namespace: commento
  labels:
    app.kubernetes.io/name: commento
---
apiVersion: v1
kind: Service
metadata:
  name: commento
  namespace: commento
  labels:
    app.kubernetes.io/name: commento
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app.kubernetes.io/name: commento
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commento
  namespace: commento
  labels:
    app.kubernetes.io/name: commento
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: commento
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: commento
        eevans.me/postgres-access: 'true'
      annotations:
        eevans.me/secret-ref: 8670f
    spec:
      serviceAccountName: commento
      containers:
        - name: commento
          image: caroga/commentoplusplus:v1.8.7
          env:
            - name: COMMENTO_ORIGIN
              value: https://commento.eevans.me
            - name: COMMENTO_PORT
              value: '8080'
            - name: COMMENTO_FORBID_NEW_OWNERS
              value: 'true'
            - name: COMMENTO_ENABLE_LOGGING
              value: 'true'
          envFrom:
            - secretRef:
                name: commento
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 6
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 98080
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: commento
  namespace: commento
  labels:
    app.kubernetes.io/name: commento
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
   - hosts:
     - commento.eevans.me
     secretName: commento-admin-tls
  rules:
  - host: commento.eevans.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: commento
            port:
              name: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: commento
  namespace: commento
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: commento
  minAvailable: 1
