---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commento
  namespace: commento
  labels:
    app.kubernetes.io/name: commento
---
apiVersion: v1
kind: Service
metadata:
  name: commento
  namespace: commento
  labels:
    app.kubernetes.io/name: commento
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app.kubernetes.io/name: commento
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commento
  namespace: commento
  labels:
    app.kubernetes.io/name: commento
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: commento
  template:
    metadata:
      labels:
        app.kubernetes.io/name: commento
        eevans.me/postgres-access: 'true'
      annotations:
        eevans.me/secret-ref: 174d7
    spec:
      serviceAccountName: commento
      containers:
        - name: commento
          image: registry.gitlab.com/commento/commento:v1.8.0
          env:
            - name: COMMENTO_ORIGIN
              value: https://commento.eevans.me
            - name: COMMENTO_BIND_ADDRESS
              value: 0.0.0.0
          envFrom:
            - secretRef:
                name: commento
          securityContext:
            runAsNonRoot: true
            runAsUser: 98080
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: commento
  namespace: commento
  labels:
    app.kubernetes.io/name: commento
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
   - hosts:
     - commento.eevans.me
     secretName: commento-admin-tls
  rules:
  - host: commento.eevans.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: commento
            port:
              name: http
