---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-keycloak-test-db
  namespace: crdb
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: crdb
          image: cockroachdb/cockroach:v23.1.11
          volumeMounts:
            - name: client-certs
              mountPath: /cockroach/cockroach-certs/
              readOnly: true
          command:
            - cockroach
            - sql
            - --certs-dir=/cockroach/cockroach-certs
            - --host=crdb-public
            - --execute="CREATE DATABASE keycloaktest; CREATE USER keycloaktest; ALTER DATABASE keycloaktest OWNER TO keycloaktest;"
      volumes:
        - name: client-certs
          projected:
            sources:
              - secret:
                  name: crdb-node
                  items:
                    - key: ca.crt
                      path: ca.crt
              - secret:
                  name: crdb-root
                  items:
                    - key: tls.crt
                      path: client.root.crt
                    - key: tls.key
                      path: client.root.key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crdb-keycloaktest
  namespace: crdb
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "keycloak-test"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "keycloak-test"
  commonName: keycloaktest
  dnsNames:
    - keycloaktest
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: crdb-issuer
  secretName: crdb-keycloaktest-cert
  usages:
    - digital signature
    - key encipherment
    - client auth
