---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dnsupdate
  namespace: dnsupdate
spec:
  interval: 5m
  chart:
    spec:
      chart: ./k8s/charts/dnsupdate
      sourceRef:
        kind: GitRepository
        name: eevans-infra
        namespace: flux-system
      interval: 1m
  values:
    host: lan.eevans.me
    zoneName: eevans.me
