---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea-redis
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 18.4.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    architecture: replication
    auth:
      enabled: false
      sentinel: false
    master:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
      persistence:
        size: 1Gi
    replica:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
      persistence:
        size: 1Gi
    sentinel:
      enabled: true
      masterSet: gitea
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
    networkPolicy:
      enabled: true
      allowExternal: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea-db
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 9.4.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    postgresqlUsername: gitea
    postgresqlDatabase: gitea
    existingSecret: gitea-postgres
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-config-gitea
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: ./k8s/charts/postgres-config
      sourceRef:
        kind: GitRepository
        name: eevans-infra
        namespace: flux-system
      interval: 1m
  values:
    postgresService: gitea-db-postgresql-headless

    backups:
      enabled: true
      repositoryName: b2:eevans-lan-db-backups:gitea
      postgresql:
        host: gitea-db-postgresql-0
        database: gitea
        user: gitea
      postgresCredentials:
        name: gitea-postgres
        key: postgresql-password
      healthCheckURL: https://hc-ping.com/5ec5e1a4-7ce6-49df-bf77-9234e6e69a8c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  labels:
    app.kubernetes.io/name: gitea
  namespace: gitea
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: 9.6.1
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 1m
  values:
    image:
      rootless: true
    replicaCount: 1
    containerSecurityContext:
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
    gitea:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      config:
        server:
          ROOT_URL: https://gitea.eevans.me/
          WEBHOOK_DELIVER_TIMEOUT: '20'
        cache:
          ENABLED: true
          ADAPTER: redis
          HOST: redis+sentinel://gitea-redis:26379/0?master_name=gitea
        indexer:
          ISSUE_INDEXER_TYPE: db
          REPO_INDEXER_ENABLED: false
        queue:
          TYPE: redis
          CONN_STR: redis+sentinel://gitea-redis:26379/0?master_name=gitea
        session:
          PROVIDER_CONFIG: redis+sentinel://gitea-redis:26379/0?master_name=gitea
        log:
          COLORIZE: "false"
        webhook:
          ALLOWED_HOST_LIST: private
        'cron.GIT_GC_REPOS':
          ENABLED: false
        actions:
          ENABLED: "true"
        repository.signing:
          SIGNING_KEY: 5C8BB2B8C941976D6C93B428192B3F842824E1F6
          SIGNING_NAME: EEvans Gitea
          SIGNING_EMAIL: gitea@eevans.co
          INITIAL_COMMIT: always
          MERGES: pubkey
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    redis-cluster:
      enabled: false
    deployment:
      labels:
        gitea-redis-client: "true"
      env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
    service:
      ssh:
        type: LoadBalancer
        clusterIP: "-"
        annotations:
          metallb.universe.tf/allow-shared-ip: ingress
        loadBalancerIP: 172.16.16.100
    ingress:
      enabled: true
      className: nginx
      hosts:
      - host: gitea.eevans.me
        paths:
          - path: /
            pathType: Prefix
      tls:
      -   hosts:
          - gitea.eevans.me
          secretName: gitea-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        # See https://github.com/kubernetes/ingress-nginx/issues/3715#issuecomment-471524919
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    persistence:
      enabled: true
      create: false
      claimName: gitea-data
      accessModes:
        - ReadWriteMany
    resources:
      limits:
          cpu: 750m
          memory: 1Gi
  valuesFrom:
    - kind: Secret
      name: gitea-values
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea-backup
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: ./k8s/charts/restic-backup
      sourceRef:
        kind: GitRepository
        name: eevans-infra
        namespace: flux-system
      interval: 1m
  values:
    repositoryName: b2:eevans-lan-gitea-backup
    secretName: gitea-backup
    healthCheckURL: https://hc-ping.com/4099aa0b-99aa-46b0-9c8e-3e6057df1653
    data:
      claimName: gitea-data
    cache:
      storageClass: rook-ceph-block
---
apiVersion: batch/v1
kind: Job
metadata:
  name: import-gitea-key-77932
  namespace: gitea
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: import-key
          # Use gitea image to prevent GPG version mismatch mishaps
          image: gitea/gitea:1.21.1-rootless
          command: [gpg, --import, /gpg/key.asc]
          volumeMounts:
            - mountPath: /data
              name: data
            - name: gpg
              mountPath: /gpg
              readOnly: true
          env:
            - name: HOME
              value: /data/gitea/git
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea-data
        - name: gpg
          secret:
            secretName: gitea-gpg-key
