---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: golinks
  namespace: golinks
spec:
  interval: 5m
  chart:
    spec:
      chart: ./k8s/charts/golinks
      sourceRef:
        kind: GitRepository
        name: eevans-infra
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      ingressClassName: cilium
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: go
          paths:
            - /
        - host: go.eevans.me
          paths:
            - /

    resources:
      requests:
        cpu: 30m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
