---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-data
  labels:
    app.kubernetes.io/name: home-assistant
  namespace: iot
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
