---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kepler
  namespace: kepler
spec:
  interval: 5m
  chart:
    spec:
      chart: kepler
      version: 0.5.3
      sourceRef:
        kind: HelmRepository
        name: kepler
        namespace: flux-system
      interval: 1m
  values:
    serviceMonitor:
      enabled: true
    canMount:
      usrSrc: true
