---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kratos
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      chart: kratos
      version: 0.38.1
      sourceRef:
        kind: HelmRepository
        name: ory
        namespace: flux-system
      interval: 1m
  values:
    global:
      dnsDomain: eevans.me
    kratos:
      config:
        dsn: cockroach://kratos@crdb-public.crdb.svc.cluster.local:26257/kratos?sslmode=verify-full&sslrootcert=/pgcert/ca.crt&sslcert=/pgcert/tls.crt&sslkey=/pgcert/tls.key
        selfservice:
          default_browser_return_url: https://kratos.eevans.me
        identity:
          schemas:
            - id: default
              url: file:///etc/config/identity.default.schema.json
      automigration:
        enabled: true
      identitySchemas:
        "identity.default.schema.json": |
          {
            "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": "Person",
            "type": "object",
            "properties": {
              "traits": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email",
                    "title": "E-Mail",
                    "ory.sh/kratos": {
                      "credentials": {
                        "password": {
                          "identifier": true
                        }
                      },
                      "recovery": {
                        "via": "email"
                      },
                      "verification": {
                        "via": "email"
                      }
                    }
                  }
                },
                "required": [
                  "email"
                ],
                "additionalProperties": false
              }
            }
          }
    deployment:
      extraVolumes:
        - name: pgcert
          secret:
            secretName: crdb-kratos-cert
            defaultMode: 0600
      extraVolumeMounts:
        - name: pgcert
          mountPath: /pgcert
          readOnly: true
    ingress:
      public:
        enabled: true
        className: cilium
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: kratos-api.eevans.me
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: kratos-api-tls
            hosts:
              - kratos-api.eevans.me
  valuesFrom:
    - kind: Secret
      name: kratos-values
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kratos-ui
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      chart: kratos-selfservice-ui-node
      version: 0.38.1
      sourceRef:
        kind: HelmRepository
        name: ory
        namespace: flux-system
      interval: 1m
  values:
    kratosPublicUrl: https://kratos-api.eevans.me
    kratosBrowserUrl: https://kratos.eevans.me
    projectName: "EEvans LAN"
    ingress:
      enabled: true
      className: cilium
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: kratos.eevans.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: kratos-ui-tls
          hosts:
            - kratos.eevans.me
