---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plausible
  namespace: plausible
  labels:
    app.kubernetes.io/name: plausible
---
apiVersion: v1
kind: Service
metadata:
  name: plausible
  namespace: plausible
  labels:
    app.kubernetes.io/name: plausible
spec:
  ports:
    - port: 8000
      name: http
  selector:
    app.kubernetes.io/name: plausible
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible
  namespace: plausible
  labels:
    app.kubernetes.io/name: plausible
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: plausible
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plausible
    spec:
      serviceAccountName: plausible
      initContainers:
        - name: create-events-db
          image: shosti/toolbox:v1
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              echo "CREATE DATABASE IF NOT EXISTS plausible_events_db" | curl --fail "$(echo "$CLICKHOUSE_DATABASE_URL" | sed 's|/plausible_events_db||')" --data-binary @-
          envFrom:
            - secretRef:
                name: plausible
          resources:
            limits:
              cpu: 750m
              memory: 768Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
        - name: init-db
          image: plausible/analytics:v2.0.0
          command:
            - /bin/sh
            - -c
            - /entrypoint.sh db migrate
          env:
            - name: BASE_URL
              value: https://plausible.eevans.co
          envFrom:
            - secretRef:
                name: plausible
          resources:
            limits:
              cpu: 750m
              memory: 768Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
      containers:
        - name: plausible
          image: plausible/analytics:v2.0.0
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: BASE_URL
              value: https://plausible.eevans.me
          envFrom:
            - secretRef:
                name: plausible
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            failureThreshold: 6
          resources:
            limits:
              cpu: 750m
              memory: 768Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plausible
  namespace: plausible
  labels:
    app.kubernetes.io/name: plausible
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: cilium
  tls:
   - hosts:
     - plausible.eevans.me
     secretName: plausible-admin-tls
  rules:
  - host: plausible.eevans.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plausible
            port:
              name: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: plausible
  namespace: plausible
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: plausible
  minAvailable: 1
