---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plausible
  namespace: plausible
  labels:
    app.kubernetes.io/name: plausible
---
apiVersion: v1
kind: Service
metadata:
  name: plausible
  namespace: plausible
  labels:
    app.kubernetes.io/name: plausible
spec:
  ports:
    - port: 8000
      name: http
  selector:
    app.kubernetes.io/name: plausible
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible
  namespace: plausible
  labels:
    app.kubernetes.io/name: plausible
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: plausible
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plausible
        eevans.me/postgres-access: 'true'
        eevans.me/public: 'true'
    spec:
      serviceAccountName: plausible
      initContainers:
        - name: create-events-db
          image: shosti/toolbox:v1
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              echo "CREATE DATABASE IF NOT EXISTS plausible_events_db" | curl --fail "$(echo "$CLICKHOUSE_DATABASE_URL" | sed 's|/plausible_events_db||')" --data-binary @-
          envFrom:
            - secretRef:
                name: plausible
          resources:
            requests:
              cpu: 750m
              memory: 1Gi
            limits:
              memory: 1Gi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
        - name: init-db
          image: plausible/analytics:v2.0.0
          command:
            - /bin/sh
            - -c
            - /entrypoint.sh db migrate
          env:
            - name: BASE_URL
              value: https://plausible.eevans.co
          envFrom:
            - secretRef:
                name: plausible
          resources:
            limits:
              cpu: 750m
              memory: 768Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
      containers:
        - name: plausible
          image: plausible/analytics:v2.0.0
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: BASE_URL
              value: https://plausible.eevans.me
          envFrom:
            - secretRef:
                name: plausible
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            failureThreshold: 6
          resources:
            limits:
              cpu: 750m
              memory: 768Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plausible
  namespace: plausible
  labels:
    app.kubernetes.io/name: plausible
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: cilium
  tls:
   - hosts:
     - plausible.eevans.me
     secretName: plausible-admin-tls
  rules:
  - host: plausible.eevans.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plausible
            port:
              name: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: plausible
  namespace: plausible
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: plausible
  minAvailable: 1
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: plausible
  namespace: plausible
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: plausible
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: postgres
      toPorts:
        - ports:
            - port: "5432"
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: clickhouse
      toPorts:
        - ports:
            - port: "8123"
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - {}
    - toFQDNs:
        - matchName: email-smtp.us-west-2.amazonaws.com
      toPorts:
        - ports:
            - port: "465"
    - toFQDNs:
        - matchName: data.iana.org
      toPorts:
        - ports:
            - port: "443"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: plausible-public
  namespace: plausible
spec:
  parentRefs:
  - name: ingress-public
    namespace: ingress-public
  labels:
    app.kubernetes.io/name: plausible
  hostnames:
    - plausible.eevans.co
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /js
    - path:
        type: PathPrefix
        value: /api
    - path:
        type: PathPrefix
        value: /auth/google
    backendRefs:
    - name: plausible
      port: 8000
