---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres
  namespace: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  teamId: "eevans"
  volume:
    size: 30Gi
  numberOfInstances: 2
  users:
    plausible: []
  databases:
    plausible: plausible
  postgresql:
    version: "15"
  resources:
    requests:
      cpu: 750m
      memory: 1Gi
    limits:
      cpu: '4'
      memory: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres
  namespace: postgres
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector:
            matchLabels:
              eevans.me/postgres-access: "true"
      ports:
        - port: 5432
  egress:
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: truenas-storage
      ports:
        - port: 9000
