---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres
  namespace: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  teamId: "eevans"
  volume:
    size: 30Gi
  numberOfInstances: 2
  users:
    plausible: []
  databases:
    plausible: plausible
  postgresql:
    version: "15"
  resources:
    requests:
      cpu: 750m
      memory: 1Gi
    limits:
      cpu: '4'
      memory: 1Gi
  sidecars:
    - name: exporter
      image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
      ports:
        - name: metrics
          containerPort: 9187
      resources:
        requests:
          cpu: 100m
          memory: 256M
        limits:
          memory: 256M
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: postgres
  namespace: postgres
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
    - fromEndpoints:
        - matchLabels:
            io.cilium.k8s.namespace.labels.eevans.me/postgres-access: "true"
      toPorts:
        - ports:
            - port: "5432"
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: postgres-operator
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "9187"
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: truenas-storage
      toPorts:
        - ports:
            - port: "9000"
    - toEndpoints:
        - {}
    - toEntities:
        - kube-apiserver
