---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres
  namespace: postgres
spec:
  teamId: "eevans"
  volume:
    size: 30Gi
  numberOfInstances: 2
  users:
    plausible: []
  databases:
    plausible: plausible
  postgresql:
    version: "15"
  resources:
    requests:
      cpu: '1'
      memory: 1Gi
    limits:
      memory: 1Gi
