apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "dnsupdate.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  failedJobsHistoryLimit: 0 # random failures cause annoying alerts
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "dnsupdate.labels" . | nindent 12 }}
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              env:
                - name: HOST
                  value: {{ .Values.host }}
                - name: ZONE_NAME
                  value: {{ .Values.zoneName }}
                - name: API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.apiTokenSecret }}
                      key: apiToken
