#!/usr/bin/env bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
VERSION="$(cat "$DIR/VERSION")"

docker buildx build . --progress=plain -t "shosti/local-drive-provisioner:$VERSION" --platform=linux/amd64 --push
