---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: postgres-operator
      version: 1.10.1
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-charts
        namespace: flux-system
      interval: 1m
  values:
    enableJsonLogging: true
