---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: postgres-backup
  namespace: postgres-operator
spec:
  generateBucketName: postgres-backup
  storageClassName: rook-ceph-bucket
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env
  namespace: postgres-operator
data:
  ALLOW_NOSSL: 'true'
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: postgres-operator
      version: 1.10.1
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-charts
        namespace: flux-system
      interval: 1m
  values:
    enableJsonLogging: true
    configKubernetes:
      pod_environment_configmap: postgres-env
      pod_environment_secret: postgres-env
      # The default configuration set it so the master can never be disrupted,
      # see https://github.com/zalando/postgres-operator/pull/384
      enable_pod_disruption_budget: false
      share_pgsocket_with_sidecars: true
      inherited_labels:
        - app.kubernetes.io/name
