apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "heimdal-kdc.fullname" . }}
  labels:
    {{- include "heimdal-kdc.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "heimdal-kdc.fullname" . }}-headless
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "heimdal-kdc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "heimdal-kdc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "heimdal-kdc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-kdc
              containerPort: 88
              protocol: TCP
            - name: udp-kdc
              containerPort: 88
              protocol: UDP
          env:
            - name: REALM
              value: "{{ .Values.config.realm }}"
            - name: KDC_ADDRESS
              value: "{{ .Values.config.kdcAddress }}"
          volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data
              readOnly: false
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: 88
          readinessProbe:
            tcpSocket:
              port: 88
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secrets
          secret:
            secretName: "{{ .Values.config.secretName }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}
