# This is basically a "virtual RPi" to act as a(nother) backup DNS server. I
# hate when DNS dies!
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: netsvc2
  namespace: netsvc
  labels:
    app.kubernetes.io/name: netsvc2
    eevans.me/type: vm
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app.kubernetes.io/name: netsvc2
        eevans.me/type: vm
    spec:
      terminationGracePeriodSeconds: 600
      domain:
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            cpu: 250m
        devices:
          disks:
            - name: bootdrive
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: dc-net
              sriov: {}
              macAddress: ee:85:dc:12:5d:4a
      networks:
        - name: dc-net
          multus:
            networkName: default/dc-net
      volumes:
        - name: bootdrive
          dataVolume:
            name: ubuntu-boot
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBwhzPdTwHKLdFXmOIBP58nO0u+iQVb98jH+BLYiG7VINuQ7SF3dB/odVbyxj3DWZxm99gRW5ofvkLSlqA96uLSsJnsJ7QkJNwEDrHK00W9TRdBHHwjivR4BPLcWyp6why0tmabJSNl171y4dm60I7xQ/sKRzr7mowkIXGTIn6ohgUwNOUFPSQGJXYQxVtAUFyFOIEg8jepY+vy2rOl/VdTZccI/4YjTgISf/OTRlvbS+WBAwMUi7j7oSvYjCgR4Ql68BDp6FCgTmyHkYlwszVCsvDDgGnC7h2z6oRgHBgP8nlSSOhNwSmJfUMZ162mFlyoTX6EcbPn0O7dkzvScZO0CdTM5hWrx6X/lnSvvnZcsnA+fqqwt0qpAiZ3HXAeZtxBCaPwmbepqMII+3zXyFXDtF6h8083yOAsnW3o0GKm/nN31SLSpXaDpogjrZo6E5Q0NESPaoad3+cDX+D/Ohz51+9VbFyr9Uf2g8yCHif+9VQy3PW8kFfjJ0H2cPci0ECcNjw4RDjNEg0X3jyY1tDpCcdSJnTZP0YYTEE1TtBVB4afSjXauL7dL5X58jLjixinekjvUDUb01hoI5An/xst+lHUxGVxHUQjkkGahxKMFO6X37V0Cxk63PnaGHvljAGO9TiqdtxFwo9+mjspydVOUneRt/Yw0oQWndtjS8jew==
  dataVolumeTemplates:
    - metadata:
        name: ubuntu-boot
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi
        source:
          pvc:
            name: ubuntu-2204
            namespace: netsvc
