---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: storage
  namespace: truenas-storage
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app.kubernetes.io/name: storage
        eevans.me/type: vm
    spec:
      terminationGracePeriodSeconds: 600
      domain:
        resources:
          limits:
            memory: 8Gi
            cpu: 3
        devices:
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - name: http
                  port: 80
                - name: https
                  port: 443
                - name: nfsv4
                  port: 2049
            - name: user-net
              acpiIndex: 4
              sriov: {}
              macAddress: ee:b5:cc:d6:7b:b0
          disks:
          - name: bootdrive
            bootOrder: 1
            disk:
              bus: sata
          hostDevices:
            - deviceName: "broadcom.com/LSI_SAS2008"
              name: hba0
      networks:
        - name: default
          pod: {}
        - name: user-net
          multus:
            networkName: default/user-net
      readinessProbe:
        periodSeconds: 30
        initialDelaySeconds: 60
        httpGet:
          port: http
      livenessProbe:
        initialDelaySeconds: 600
        periodSeconds: 30
        failureThreshold: 10
        httpGet:
          port: http
      volumes:
        - name: bootdrive
          persistentVolumeClaim:
            claimName: truenas-storage-boot
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: truenas-storage
  labels:
    app.kubernetes.io/name: storage
  annotations:
    external-dns.alpha.kubernetes.io/hostname: storage.internal.eevans.me.
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
    - name: nfsv4
      port: 2049
      protocol: TCP
      targetPort: nfsv4
  selector:
    app.kubernetes.io/name: storage
    eevans.me/type: vm
---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: storage
  namespace: truenas-storage
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
      - https://storage.internal.eevans.me/ui/
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: storage
  namespace: truenas-storage
spec:
  groups:
  - name: storage.truenas
    rules:
    - alert: StorageServerDown
      annotations:
        summary: Storage server is unavailable
      expr: probe_success{job="probe/truenas-storage/storage",namespace="truenas-storage"} != 1
      for: 5m
      labels:
        severity: critical
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: storage-internal
  namespace: truenas-storae
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: storage
  ingress:
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "2049"
    - fromEntities:
        - remote-node
      toPorts:
        - ports:
            - port: "2049"
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "443"
