---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 1m
  values:
    upgradeCompatibility: "1.10"
    kubeProxyReplacement: "true"
    k8sServiceHost: k8s.eevans.me
    k8sServicePort: 6443
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: ["10.101.0.0/16"]
    cni:
      exclusive: false
    bpf:
      masquerade: true
    l7Proxy: true
    envoy:
      enabled: true
    encryption:
      enabled: true
      nodeEncryption: true
      type: wireguard
    gatewayAPI:
      enabled: true
    ingressController:
      enabled: true
      loadbalancerMode: dedicated
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    dashboards:
      enabled: true
      namespace: monitoring
    hubble:
      enabled: true
      listenAddress: ":4244"
      ui:
        enabled: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
          hosts:
            - hubble.eevans.me
          tls:
            - hosts:
                - hubble.eevans.me
              secretName: hubble-ui-tls
        backend:
          resources:
            limits:
              memory: 128Mi
        frontend:
          resources:
            limits:
              memory: 128Mi
        proxy:
          resources:
            limits:
              memory: 128Mi
      relay:
        enabled: true
        resources:
          limits:
            memory: 256Mi
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
          - http
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
          namespace: monitoring
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
        namespace: monitoring
      resources:
        limits:
          memory: 256Mi
    resources:
      limits:
        memory: 512Mi
