---
apiVersion: v1
kind: Namespace
metadata:
  name: cdi
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: dnsupdate
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: v1
kind: Namespace
metadata:
  name: golinks
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-public
---
apiVersion: v1
kind: Namespace
metadata:
  name: iot
---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    eevans.me/public: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: unifi
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: Namespace
metadata:
  name: truenas-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: sriov-network-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: eevansco
  labels:
    eevans.me/public: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: reboot-coordinator
---
apiVersion: v1
kind: Namespace
metadata:
  name: paperless
---
apiVersion: v1
kind: Namespace
metadata:
  name: apcups
---
apiVersion: v1
kind: Namespace
metadata:
  name: trivy-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: listmonk
  labels:
    eevans.me/public: "true"
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: netsvc
---
apiVersion: v1
kind: Namespace
metadata:
  name: crdb
---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-operator
  labels:
    eevans.me/mariadb-access: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: v1
kind: Namespace
metadata:
  name: ghost
  labels:
    eevans.me/mariadb-access: 'true'
    eevans.me/public: "true"
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: eevansco-static
  labels:
    eevans.me/public: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: zookeeper
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: Namespace
metadata:
  name: plausible
