apiVersion: v1
kind: Service
metadata:
  name: cdi-uploadproxy-lb
  namespace: cdi
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cdi-upload.eevans.me.
    external-dns.alpha.kubernetes.io/ttl: "1m"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
