#!/usr/bin/env bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
VERSION="$(cat "$DIR/VERSION")"

docker build . -t "shosti/clevis:$VERSION"
docker push "shosti/clevis:$VERSION"
