---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: 1.12.8
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 1m
  values:
    logLevel: DEBUG
    resources:
      limits:
        memory: 512Mi
    pspEnable: false
    monitoring:
      enabled: true
      createPrometheusRules: true
