---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-source-controller
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchLabels:
      app: source-controller
  podMetricsEndpoints:
  - port: http-prom
