---
# tasks file for tang_server
- name: Ensure opt volume is mounted
  command: mountpoint /opt
  changed_when: False
  when: rpi_data_volume_tang_server is defined

- name: Install tang
  apt:
    name: tang
    state: present

- name: Add custom tang configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  loop:
    - tangd-keygen.service
    - tangd@.service
    - tangd.socket
    - tangd-update.path
    - tangd-update.service
  notify: systemd reload

- name: Enable tangd
  systemd:
    name: tangd.socket
    enabled: true
    state: started

- name: Allow tang firewall access
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "{{ tang_server_port }}"

- include_tasks: backup.yml
