---
- hosts: localhost

  tasks:
    - name: Set up execution environment
      awx.awx.execution_environment:
        name: awx-ee-2.11
        image: harbor.eevans.me/library/awx-ee:2.11
        organization: Default
        pull: always

    - name: Set up EEvans Infra project
      awx.awx.project:
        name: EEvans Infra
        organization: Default
        scm_type: git
        scm_url: git@gitea-ssh.gitea.svc.cluster.local:shosti/eevans-infra.git
        scm_branch: master
        default_environment: awx-ee-2.11
        credential: Git Deploy Key
        scm_update_on_launch: true
        scm_clean: true

    - name: Add EEvans Infra inventory
      awx.awx.inventory:
        name: EEvans Infra
        organization: Default

    - name: Add EEvans Infra git source
      awx.awx.inventory_source:
        name: EEvans Infra
        inventory: EEvans Infra
        organization: Default
        source: scm
        source_project: EEvans Infra
        source_path: ansible/inventory
        update_on_launch: true

    - name: Add NetSVC job template
      awx.awx.job_template:
        name: NetSVC
        organization: Default
        playbook: ansible/netsvc.yml
        project: EEvans Infra
        inventory: EEvans Infra
        credentials:
          - Ubuntu SSH Key
          - Vault Password
        execution_environment: awx-ee-2.11
        job_type: run
        webhook_service: github

    - name: Add VyOS job template
      awx.awx.job_template:
        name: VyOS
        organization: Default
        playbook: ansible/vyos.yml
        project: EEvans Infra
        inventory: EEvans Infra
        credentials:
          - VyOS Deploy
          - Vault Password
        execution_environment: awx-ee-2.11
        job_type: run
        webhook_service: github
