roles:
  - src: geerlingguy.swap
    version: 1.2.0

collections:
  - name: ansible.posix
    version: 1.3.0
    source: https://galaxy.ansible.com

  - name: community.general
    version: 3.8.0
    source: https://galaxy.ansible.com

  - name: community.docker
    version: 1.10.0
    source: https://galaxy.ansible.com

  - name: vyos.vyos
    version: 4.1.0
    source: https://galaxy.ansible.com
