---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apcups-device-driver.yaml
  - clusterissuer.yaml
  - external-dns-coredns.yaml
  - external-dns-etcd.yaml
  - external-dns.yaml
  - external-monitoring.yaml
  - ingress-nginx.yaml
  - ingress-public.yaml
  - local-drive-provisioner.yaml
  - local-path-storage.yaml
  - logging.yaml
  - metallb-system.yaml
  - metallb.yaml
  - monitoring.yaml
  - node-inotify.yaml
  - oauth2-proxy.yaml
  - snmp.yaml
  - sriov.yaml
