# See: https://www.esphome-devices.com/devices/Sonoff-S31

# Basic Config
esphome:
  name: tv_plug
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: dumbhome
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.51.48.100
    gateway: 10.51.48.1
    subnet: 255.255.252.0

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
api:
  password: !secret api_password
ota:
  password: !secret api_password

# Device Specific Config

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "TV Plug Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "TV Plug Status"

sensor:
  - platform: wifi_signal
    name: "TV Plug WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    update_interval: 2s
    current:
      name: "TV Plug Current"
      accuracy_decimals: 1
    voltage:
      name: "TV Plug Voltage"
      accuracy_decimals: 1
    power:
      name: "TV Plug Power"
      accuracy_decimals: 1
switch:
  - platform: gpio
    name: "TV Plug Relay"
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13
