apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    password_file /mosquitto/secrets/passwd
    listener 1883

    {{- if .Values.tls.enabled }}
    listener 8883
    certfile /mosquitto/tls/tls.crt
    keyfile /mosquitto/tls/tls.key
    {{- end }}
