apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
    {{- if .Values.tls.enabled }}
    - port: 8883
      targetPort: mqtt-tls
      protocol: TCP
      name: mqtt-tls
    {{- end }}
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}-headless
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
