apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ include "mosquitto.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "mosquitto.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mosquitto.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mosquitto.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            {{- if .Values.tls.enabled }}
            - name: mqtt-tls
              containerPort: 8883
              protocol: TCP
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: mqtt{{ if .Values.tls.enabled }}-tls{{ end }}
          livenessProbe:
            tcpSocket:
              port: mqtt{{ if .Values.tls.enabled }}-tls{{ end }}
            initialDelaySeconds: 10
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config
              readOnly: true
            - name: passwd
              mountPath: /mosquitto/secrets
              readOnly: true
          {{- if .Values.tls.enabled }}
            - name: tls
              mountPath: /mosquitto/tls
              readOnly: true
          {{- end }}
          {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /mosquitto/data
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "mosquitto.fullname" . }}
        - name: passwd
          secret:
            secretName: {{ .Values.passwdSecret.name }}
            items:
              - key: {{ .Values.passwdSecret.key }}
                path: passwd
        {{- if .Values.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName }}
        {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}
