{{- if .Values.backups.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgres-config.serviceAccountName" . }}
  labels:
{{ include "postgres-config.labels" . | nindent 4 }}
{{- end }}
