apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monica.fullname" . }}
  labels:
    {{- include "monica.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "monica.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "monica.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "monica.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_ENV
              value: {{ .Values.app.env }}
            - name: APP_URL
              value: {{ .Values.app.url }}
            - name: DB_HOST
              value: {{ .Values.db.host }}
            - name: DB_DATABASE
              value: {{ .Values.db.database }}
            - name: DB_USERNAME
              value: {{ .Values.db.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.db.passwordSecret | nindent 18 }}
            {{- range .Values.app.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.envSecret }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: storage
              mountPath: /var/www/html/storage
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /security.txt
              port: http
          readinessProbe:
            httpGet:
              path: /security.txt
              port: http
          startupProbe:
            httpGet:
              path: /security.txt
              port: http
            failureThreshold: 60
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- if .Values.persistence.enabled }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "monica.pvcName" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
