apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.fullname" . }}-secret-key
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secret-key" (include "paperless.fullname" .))) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKey := (get $secretData "secretKey") | default (randAlphaNum 64 | b64enc) }}
  secretKey: {{ $secretKey | quote }}
