apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb-operator
      version: 0.24.0
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval: 1m
  values:
    metrics:
      enabled: true
    webhook:
      cert:
        certManager:
          enabled: true
